version: "3.2"

services: 
  explorer:
    image: "jochemin/dojo-explorer:latest"
    container_name: dojo-explorer
    restart: on-failure
    volumes:
      - ./.env:/workspace/.env
    networks:
      dmznet:
        ipv4_address: 172.29.1.6
      dojonet:
        ipv4_address: 172.28.1.6
networks:
   my-dojo_dojonet:
    external: true
   my-dojo_dmznet:
    external: true
